config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :event_export_files

  resources :event_import_files

  resources :events
  resources :event_categories
  resources :event_import_results, only: [:index, :show, :destroy]
  resources :participates
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  include MasterModel
  default_scope { order('position') }
  has_many :events

  translates :display_name
  paginates_per 10
end

# == Schema Information
#
# Table name: event_categories
#
#  id                        :integer          not null, primary key
#  name                      :string           not null
#  display_name              :text
#  note                      :text
#  position                  :integer
#  created_at                :datetime
#  updated_at                :datetime
#  display_name_translations :jsonb            not null
#

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  before_action :set_event_category, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]

  # GET /event_categories
  # GET /event_categories.json
  def index
    @event_categories = EventCategory.order(:position)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_categories }
    end
  end

  # GET /event_categories/1
  # GET /event_categories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_category }
    end
  end

  # GET /event_categories/new
  # GET /event_categories/new.json
  def new
    @event_category = EventCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_category }
    end
  end

  # GET /event_categories/1/edit
  def edit
  end

  # POST /event_categories
  # POST /event_categories.json
  def create
    @event_category = EventCategory.new(event_category_params)

    respond_to do |format|
      if @event_category.save
        format.html { redirect_to @event_category, notice:  t('controller.successfully_created', model:  t('activerecord.models.event_category')) }
        format.json { render json: @event_category, status: :created, location: @event_category }
      else
        format.html { render action: "new" }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_categories/1
  # PUT /event_categories/1.json
  def update
    if params[:move]
      move_position(@event_category, params[:move])
      return
    end

    respond_to do |format|
      if @event_category.update(event_category_params)
        format.html { redirect_to @event_category, notice:  t('controller.successfully_updated', model:  t('activerecord.models.event_category')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_categories/1
  # DELETE /event_categories/1.json
  def destroy
    @event_category.destroy

    respond_to do |format|
      format.html { redirect_to event_categories_url, notice: t('controller.successfully_deleted', model: t('activerecord.models.event_category')) }
      format.json { head :no_content }
    end
  end

  private
  def set_event_category
    @event_category = EventCategory.find(params[:id])
    authorize @event_category
  end

  def check_policy
    authorize EventCategory
  end

  def event_category_params
    params.require(:event_category).permit(:name, :display_name, :note)
  end
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
  def select_checkin_date
    [[t('activerecord.attributes.event_category.checkin_ng_post'), 1], [t('activerecord.attributes.event_category.checkin_ng_pre'), 2]]
  end
end

app/views/event_categories/_form.html.erb
<%= form_for(@event_category) do |f| %>
  <%= f.error_messages %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :display_name %>
    <%= f.text_area :display_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :note %>
    <%= f.text_area :note, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/event_categories/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.editing', model: t('activerecord.models.event_category')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.show'), @event_category -%></li>
        <li><%= link_to t('page.back'), event_categories_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/event_categories/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.listing', model: t('activerecord.models.event_category')) -%></h1>

    <table class="table table-striped index">
      <tr>
        <th id="position"></th>
        <th><%= t('activerecord.attributes.event_category.name') -%></th>
        <th>
          <%= t('activerecord.attributes.event_category.display_name') -%>
          /
          <%= t('activerecord.attributes.event_category.note') -%>
        </th>
        <th></th>
      </tr>

      <%- @event_categories.each do |event_category| -%>
        <tr class="line<%= cycle("0", "1") -%>">
          <td>
            <%- if policy(event_category).update? -%>
              <%= move_position(event_category) -%>
            <%- end -%>
          </td>
          <td><%= event_category.name -%></td>
          <td>
            <%= link_to event_category.display_name, event_category -%>
            <br />
            <%= event_category.note %>
          </td>
          <td>
            <%- if policy(event_category).update? -%>
              <%= link_to t('page.edit'), edit_event_category_path(event_category) -%>
            <% end %>
            <%- if policy(event_category).destroy? -%>
              <%= link_to t('page.destroy'), event_category_path(event_category), data: {confirm: t('page.are_you_sure')}, method: :delete -%>
            <%- end -%>
          </td>
        </tr>
      <%- end -%>
    </table>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(EventCategory).create? -%>
          <li><%= link_to t('page.new', model: t('activerecord.models.event_category')), new_event_category_path -%></li>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/event_categories/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.new', model: t('activerecord.models.event_category')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.back'), event_categories_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/event_categories/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.showing', model: t('activerecord.models.event_category')) -%></h1>
    <p id="notice"><%= notice %></p>

    <p>
      <strong><%= t('activerecord.attributes.event_category.name') -%>:</strong>
      <%= @event_category.name -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_category.display_name') -%>:</strong>
      <%= @event_category.display_name -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_category.note') -%>:</strong>
      <%= @event_category.note -%>
    </p>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(@event_category).update? -%>
          <li><%= link_to t('page.edit'), edit_event_category_path(@event_category) -%></li>
        <%- end -%>
        <li><%= back_to_index(flash[:page_info]) -%></li>
      </ul>
    </div>
  </div>
</div>