config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :event_export_files

  resources :event_import_files

  resources :events
  resources :event_categories
  resources :event_import_results, only: [:index, :show, :destroy]
  resources :participates
end

app/models/event_import_file.rb
class EventImportFile < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries[
    transition_class: EventImportFileTransition,
    initial_state: :pending
  ]
  include ImportFile
  scope :not_imported, -> {in_state(:pending)}
  scope :stucked, -> {in_state(:pending).where('event_import_files.created_at < ?', 1.hour.ago)}

  if ENV['ENJU_STORAGE'] == 's3'
    has_attached_file :event_import, storage: :s3,
      s3_credentials: {
        access_key: ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        bucket: ENV['S3_BUCKET_NAME'],
        s3_host_name: ENV['S3_HOST_NAME']
      },
      s3_permissions: :private
  else
    has_attached_file :event_import,
      path: ":rails_root/private/system/:class/:attachment/:id_partition/:style/:filename"
  end
  validates_attachment_content_type :event_import, content_type: [
    'text/csv',
    'text/plain',
    'text/tab-separated-values',
    'application/octet-stream',
    'application/vnd.ms-excel'
  ]
  validates_attachment_presence :event_import
  belongs_to :user
  belongs_to :default_library, class_name: 'Library', optional: true
  belongs_to :default_event_category, class_name: 'EventCategory', optional: true
  has_many :event_import_results

  has_many :event_import_file_transitions, autosave: false

  attr_accessor :mode

  def state_machine
    EventImportFileStateMachine.new(self, transition_class: EventImportFileTransition)
  end

  delegate :can_transition_to?, :transition_to!, :transition_to, :current_state,
    to: :state_machine

  def import
    transition_to!(:started)
    num = { imported: 0, failed: 0 }
    rows = open_import_file(create_import_temp_file(event_import))
    check_field(rows.first)
    row_num = 1

    rows.each do |row|
      row_num += 1
      next if row['dummy'].to_s.strip.present?
      event_import_result = EventImportResult.new(event_import_file_id: id, body: row.fields.join("\t"))

      event = Event.new
      event.name = row['name'].to_s.strip
      event.display_name = row['display_name']
      event.note = row['note']
      event.start_at = Time.zone.parse(row['start_at']) if row['start_at'].present?
      event.end_at = Time.zone.parse(row['end_at']) if row['end_at'].present?
      category = row['event_category'].to_s.strip
      if %w(t true TRUE).include?(row['all_day'].to_s.strip)
        event.all_day = true
      else
        event.all_day = false
      end
      library = Library.find_by(name: row['library'])
      library = default_library || Library.web if library.blank?
      event.library = library
      event_category = EventCategory.find_by(name: row['event_category'])
      event_category = default_event_category if event_category.blank?
      event.event_category = event_category

      if event.save
        event_import_result.event = event
        num[:imported] += 1
        if row_num % 50 == 0
          Sunspot.commit
          GC.start
        end
      else
        num[:failed] += 1
      end
      event_import_result.save!
    end
    Sunspot.commit
    rows.close
    transition_to!(:completed)
    mailer = EventImportMailer.completed(self)
    send_message(mailer)
    num
  rescue => e
    self.error_message = "line #{row_num}: #{e.message}"
    save
    transition_to!(:failed)
    mailer = EventImportMailer.failed(self)
    send_message(mailer)
    raise e
  end

  def modify
    transition_to!(:started)
    rows = open_import_file(create_import_temp_file(event_import))
    check_field(rows.first)
    row_num = 1

    rows.each do |row|
      row_num += 1
      next if row['dummy'].to_s.strip.present?
      event = Event.find(row['id'].to_s.strip)
      event_category = EventCategory.where(name: row['event_category'].to_s.strip).first
      event.event_category = event_category if event_category
      library = Library.find_by(name: row['library'].to_s.strip)
      event.library = library if library
      event.name = row['name'] if row['name'].to_s.strip.present?
      event.start_at = Time.zone.parse(row['start_at']) if row['start_at'].present?
      event.end_at = Time.zone.parse(row['end_at']) if row['end_at'].present?
      event.note = row['note'] if row['note'].to_s.strip.present?
      if %w(t true TRUE).include?(row['all_day'].to_s.strip)
        event.all_day = true
      else
        event.all_day = false
      end
      event.save!
    end
    transition_to!(:completed)
    mailer = EventImportMailer.completed(self)
    send_message(mailer)
  rescue => e
    self.error_message = "line #{row_num}: #{e.message}"
    save
    transition_to!(:failed)
    mailer = EventImportMailer.failed(self)
    send_message(mailer)
    raise e
  end

  def remove
    transition_to!(:started)
    rows = open_import_file(create_import_temp_file(event_import))
    rows.shift
    row_num = 1

    rows.each do |row|
      row_num += 1
      next if row['dummy'].to_s.strip.present?
      event = Event.find(row['id'].to_s.strip)
      event.picture_files.destroy_all # workaround
      event.reload
      event.destroy
    end
    transition_to!(:completed)
    mailer = EventImportMailer.completed(self)
    send_message(mailer)
  rescue => e
    self.error_message = "line #{row_num}: #{e.message}"
    save
    transition_to!(:failed)
    mailer = EventImportMailer.failed(self)
    send_message(mailer)
    raise e
  end

  def self.import
    EventImportFile.not_imported.each do |file|
      file.import_start
    end
  rescue
    Rails.logger.info "#{Time.zone.now} importing events failed!"
  end

  private

  def open_import_file(tempfile)
    file = CSV.open(tempfile, col_sep: "\t")
    header_columns = EventImportResult.header
    header = file.first
    ignored_columns = header - header_columns
    unless ignored_columns.empty?
      self.error_message = I18n.t('import.following_column_were_ignored', column: ignored_columns.join(', '))
      save!
    end
    rows = CSV.open(tempfile, headers: header, col_sep: "\t")
    event_import_result = EventImportResult.new
    event_import_result.assign_attributes({ event_import_file_id: id, body: header.join("\t") })
    event_import_result.save!
    tempfile.close(true)
    file.close
    rows
  end

  def check_field(field)
    if [field['name']].reject{|f| f.to_s.strip == ""}.empty?
      raise "You should specify a name in the first line"
    end
    if [field['start_at'], field['end_at']].reject{|field| field.to_s.strip == ""}.empty?
      raise "You should specify dates in the first line"
    end
  end
end

# == Schema Information
#
# Table name: event_import_files
#
#  id                        :integer          not null, primary key
#  parent_id                 :integer
#  content_type              :string
#  size                      :integer
#  user_id                   :integer
#  note                      :text
#  executed_at               :datetime
#  event_import_file_name    :string
#  event_import_content_type :string
#  event_import_file_size    :integer
#  event_import_updated_at   :datetime
#  edit_mode                 :string
#  created_at                :datetime
#  updated_at                :datetime
#  event_import_fingerprint  :string
#  error_message             :text
#  user_encoding             :string
#  default_library_id        :integer
#  default_event_category_id :integer
#

app/controllers/event_import_files_controller.rb
class EventImportFilesController < ApplicationController
  before_action :set_event_import_file, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]
  before_action :prepare_options, only: [:new, :edit]

  # GET /event_import_files
  # GET /event_import_files.json
  def index
    @event_import_files = EventImportFile.order(created_at: :desc).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_import_files }
    end
  end

  # GET /event_import_files/1
  # GET /event_import_files/1.json
  def show
    @event_import_results = @event_import_file.event_import_results.page(params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_import_file }
      format.download {
        send_data @event_import_file.attachment.download, filename: @event_import_file.attachment.filename.to_s, type: @event_import_file.attachment.content_type
      }
    end
  end

  # GET /event_import_files/new
  # GET /event_import_files/new.json
  def new
    @event_import_file = EventImportFile.new
    @event_import_file.default_library = current_user.profile.library
    @event_import_file.default_event_category = @event_categories.first

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_import_file }
    end
  end

  # GET /event_import_files/1/edit
  def edit
  end

  # POST /event_import_files
  # POST /event_import_files.json
  def create
    @event_import_file = EventImportFile.new(event_import_file_params)
    @event_import_file.user = current_user

    respond_to do |format|
      if @event_import_file.save
        if @event_import_file.mode == 'import'
          EventImportFileJob.perform_later(@event_import_file)
        end
        format.html { redirect_to @event_import_file, notice: t('import.successfully_created', model: t('activerecord.models.event_import_file')) }
        format.json { render json: @event_import_file, status: :created, location: @event_import_file }
      else
        prepare_options
        format.html { render action: "new" }
        format.json { render json: @event_import_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_import_files/1
  # PUT /event_import_files/1.json
  def update
    respond_to do |format|
      if @event_import_file.update(event_import_file_params)
        if @event_import_file.mode == 'import'
          EventImportFileJob.perform_later(@event_import_file)
        end
        format.html { redirect_to @event_import_file, notice: t('controller.successfully_updated', model: t('activerecord.models.event_import_file')) }
        format.json { head :no_content }
      else
        prepare_options
        format.html { render action: "edit" }
        format.json { render json: @event_import_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_import_files/1
  # DELETE /event_import_files/1.json
  def destroy
    @event_import_file.destroy

    respond_to do |format|
      format.html { redirect_to event_import_files_url }
      format.json { head :no_content }
    end
  end

  private
  def set_event_import_file
    @event_import_file = EventImportFile.find(params[:id])
    authorize @event_import_file
  end

  def check_policy
    authorize EventImportFile
  end

  def event_import_file_params
    params.require(:event_import_file).permit(
      :attachment, :edit_mode, :user_encoding, :mode,
      :default_library_id, :default_event_category_id
    )
  end

  def prepare_options
    @libraries = Library.all
    @event_categories = EventCategory.order(:position)
  end
end

app/views/event_import_files/_results.html.erb
<h2><%= t('activerecord.models.event_import_result') %></h2>
<p>
  <%= link_to((image_tag 'icons/page_white_excel.png', size: '16x16', class: 'enju_icon', alt: 'TSV'), event_import_results_path(event_import_file_id: @event_import_file.id, format: :txt, locale: @locale.to_s)) -%>
  (<%= link_to 'TSV', event_import_results_path(event_import_file_id: @event_import_file.id, format: :txt, locale: @locale.to_s) -%>)
</p>

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.attributes.event_import_result.lineno') %></th>
    <th><%= t('activerecord.attributes.event_import_result.body') %></th>
    <th><%= t('activerecord.models.event') %></th>
    <th></th>
  </tr>
<% @event_import_results.each_with_index do |event_import_result, idx| %>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= @event_import_results.offset_value + idx + 1 %></td>
    <td><%= event_import_result.body.inspect %></td>
    <td><%= link_to event_import_result.event.display_name, event_import_result.event if event_import_result.event %></td>
    <td>
      <%= link_to t('page.show'), event_import_result %>
      <%= link_to t('page.destroy'), event_import_result, data: {confirm: t('page.are_you_sure')}, method: :delete %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate(@event_import_results) %>

app/views/event_import_files/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.editing', model: t('activerecord.models.event_import_file')) -%></h1>

    <%= form_for(@event_import_file) do |f| -%>
      <%= f.error_messages -%>

      <div class="form-group">
        <%= f.label :event_import_file_name -%><br />
        <%= f.text_field :event_import_file_name -%>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <%- end -%>
  </div>

  <div class="row">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.show'), @event_import_file -%></li>
        <li><%= link_to t('page.back'), event_import_files_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/event_import_files/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.listing', model: t('activerecord.models.event_import_file')) -%></h1>
    <p id="notice"><%= notice %></p>

    <table class="table table-striped index">
      <thead>
        <tr>
          <th style="width: 30px">Id</th>
          <th><%= t('activerecord.attributes.event_import_file.event_import_file_name') -%></th>
          <th><%= t('activerecord.attributes.event_import_file.edit_mode') -%></th>
          <th><%= t('activerecord.attributes.event_import_file.executed_at') -%></th>
          <th><%= t('activerecord.attributes.event_import_file.state') -%></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @event_import_files.each do |event_import_file| %>
          <tr class="line<%= cycle("0", "1") -%>">
            <td><%= link_to (event_import_file.id), event_import_file -%></td>
            <td>
              <%= link_to event_import_file.attachment.blob.filename, event_import_file_path(event_import_file, format: :download) if event_import_file.attachment.attached? %>
              <br />
              <%= t('activerecord.models.user') -%>: <%= link_to event_import_file.user.username, event_import_file.user.profile if event_import_file.user.try(:profile) -%></td>
            <td><%= event_import_file.edit_mode -%></td>
            <td><%= l(event_import_file.executed_at) if event_import_file.executed_at -%></td>
            <td><%= localized_state(event_import_file.current_state) -%></td>
            <td>
              <%= link_to t('page.show'), event_import_file -%>
              <%= link_to t('page.destroy'), event_import_file, data: {confirm: t('page.are_you_sure')}, method: :delete -%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate(@event_import_files) -%>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.new', model: t('activerecord.models.event_import_file')), new_event_import_file_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/event_import_files/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.new', model: t('activerecord.models.event_import_file')) -%></h1>

    <%= form_for(@event_import_file, html: { multipart: true }) do |f| -%>
      <%= f.error_messages -%>

      <div class="form-group">
        <%= f.label t('page.file') -%><br />
        <%= f.file_field :attachment -%>
      </div>

      <div class="form-group">
        <%= f.label :edit_mode -%><br />
        <%= f.radio_button :edit_mode, 'create', checked: 'checked' %>
        <%= f.label :edit_mode, t('page.create'), value: 'create' %>
        <%= f.radio_button :edit_mode, 'update' %>
        <%= f.label :edit_mode, t('page.update'), value: 'update' %>
        <%= f.radio_button :edit_mode, 'destroy' %>
        <%= f.label :edit_mode, t('page.destroy'), value: 'destroy' %>
      </div>

      <div class="form-group">
        <%= f.label :user_encoding -%><br />
        <%= f.radio_button :user_encoding, 'auto_detect', checked: 'checked' %>
        <%= f.label :user_encoding, t('import.auto_detect'), value: 'auto_detect' %>
        <%= f.radio_button :user_encoding, 'utf-8' %>
        <%= f.label :user_encoding, 'UTF-8', value: 'utf-8' %>
        <%= f.radio_button :user_encoding, 'shift_jis' %>
        <%= f.label :user_encoding, 'Shift_JIS', value: 'shift_jis' %>
        <%= f.radio_button :user_encoding, 'euc-jp' %>
        <%= f.label :user_encoding, 'EUC-JP', value: 'euc-jp' %>
      </div>

      <div class="form-group">
        <%= f.label :default_event_category_id -%>
        <%= f.select(:default_event_category_id, @event_categories.collect{|e| [e.display_name, e.id]}) -%><br />
        <%= t('event_import_file.default_event_category') %>
      </div>

      <div class="form-group">
        <%= f.label :default_library_id -%>
        <%= f.select(:default_library_id, @libraries.collect{|l| [l.display_name, l.id]}) -%><br />
        <%= t('event_import_file.default_library') %>
      </div>

      <div class="actions">
        <%= f.hidden_field :mode, value: 'import' %>
        <%= f.submit t('page.start_import') %>
      </div>
    <%- end -%>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= back_to_index(flash[:page_info]) %></li>
      </ul>
    </div>
  </div>
</div>

app/views/event_import_files/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.showing', model: t('activerecord.models.event_import_file')) -%></h1>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Id:</strong>
      <%= @event_import_file.id -%>
    </p>

    <% if @event_import_file.attachment.attached? %>
      <p>
        <strong><%= t('activerecord.attributes.event_import_file.event_import_file_name') -%>:</strong>
        <%= link_to @event_import_file.event_import_file_name, event_import_file_path(@event_import_file, format: :download) %>
        (<%= @event_import_file.event_import_content_type -%>)
        <strong><%= t('activerecord.attributes.event_import_file.event_import_file_size') -%>:</strong>
        <%= @event_import_file.event_import_file_size -%>
      </p>
    <% end %>

    <p>
      <strong><%= t('page.created_at') -%>:</strong>
      <%= l(@event_import_file.created_at) if @event_import_file.created_at -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_import_file.executed_at') -%>:</strong>
      <%= l(@event_import_file.executed_at) if @event_import_file.executed_at -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_import_file.edit_mode') -%>:</strong>
      <%= @event_import_file.edit_mode -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_import_file.user_encoding') -%>:</strong>
      <%= @event_import_file.user_encoding -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_import_file.default_event_category_id') -%>:</strong>
      <%= link_to @event_import_file.default_event_category.display_name, @event_import_file.default_event_category if @event_import_file.default_event_category.try(:display_name) -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_import_file.default_library_id') -%>:</strong>
      <%= link_to @event_import_file.default_library.display_name, @event_import_file.default_library if @event_import_file.default_library.try(:display_name) -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_import_file.state') -%>:</strong>
      <%= localized_state(@event_import_file.current_state) -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_import_file.error_message') -%>:</strong>
      <%= simple_format(@event_import_file.error_message) -%>
    </p>

    <p>
      <strong><%= t('activerecord.models.user') -%>:</strong>
      <%= link_to @event_import_file.user.username, @event_import_file.user.profile if @event_import_file.user.try(:profile) -%>
    </p>

    <% if @event_import_results %>
      <%= render 'results' %>
    <% end %>
  </div>

  <div class="row">
    <div class="card card-body">
      <%= form_for(@event_import_file) do |f| %>
        <ul>
          <li><%= link_to t('activerecord.models.event_import_result'), event_import_results_path(event_import_file_id: @event_import_file.id) -%></li>
          <li><%= back_to_index(flash[:page_info]) -%></li>
          <% if current_user.has_role?('Administrator') %>
            <li><%= link_to 'Resque', resque_path %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>