config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :event_export_files

  resources :event_import_files

  resources :events
  resources :event_categories
  resources :event_import_results, only: [:index, :show, :destroy]
  resources :participates
end

app/models/event.rb
class Event < ApplicationRecord
  scope :closing_days, -> { includes(:event_category).where('event_categories.name' => 'closed') }
  scope :on, lambda {|datetime| where('start_at >= ? AND start_at < ?', datetime.beginning_of_day, datetime.tomorrow.beginning_of_day + 1)}
  scope :past, lambda {|datetime| where('end_at <= ?', Time.zone.parse(datetime).beginning_of_day)}
  scope :upcoming, lambda {|datetime| where('start_at >= ?', Time.zone.parse(datetime).beginning_of_day)}
  scope :at, lambda {|library| where(library_id: library.id)}

  belongs_to :event_category
  belongs_to :library
  belongs_to :place, optional: true
  has_many :picture_files, as: :picture_attachable
  has_many :participates, dependent: :destroy
  has_many :agents, through: :participates
  has_one :event_import_result

  searchable do
    text :name, :note
    integer :library_id
    time :created_at
    time :updated_at
    time :start_at
    time :end_at
  end

  validates :name, :start_at, :end_at, presence: true
  validate :check_date
  before_validation :set_date
  before_validation :set_display_name, on: :create
  translates :display_name

  paginates_per 10

  def set_date
    if all_day
      set_all_day
    end
  end

  def set_all_day
    if start_at and end_at
      self.start_at = start_at.beginning_of_day
      self.end_at = end_at.end_of_day
    end
  end

  def check_date
    if start_at and end_at
      if start_at >= end_at
        errors.add(:start_at)
        errors.add(:end_at)
      end
    end
  end

  def set_display_name
    self.display_name = name if display_name.blank?
  end

  # CSVのヘッダ
  # @param [String] role 権限
  def self.csv_header(role: 'Guest')
    Event.new.to_hash(role: role).keys
  end

  # CSV出力用のハッシュ
  # @param [String] role 権限
  def to_hash(role: 'Guest')
    {
      name: name,
      event_category: event_category.try(:name),
      library: library.try(:name),
      start_at: start_at,
      end_at: end_at,
      all_day: all_day,
      note: note,
      created_at: created_at,
      updated_at: updated_at,
      display_name: display_name
    }
  end

  # TSVでのエクスポート
  # @param [String] role 権限
  # @param [String] col_sep 区切り文字
  def self.export(role: 'Guest', col_sep: "\t")
    file = Tempfile.create('event_export') do |f|
      f.write Event.csv_header(role: role).to_csv(col_sep: col_sep)
      Event.find_each do |event|
        f.write event.to_hash(role: role).values.to_csv(col_sep: col_sep)
      end

      f.rewind
      f.read
    end
  end
end

# == Schema Information
#
# Table name: events
#
#  id                        :integer          not null, primary key
#  library_id                :integer          not null
#  event_category_id         :integer          not null
#  name                      :string
#  note                      :text
#  start_at                  :datetime
#  end_at                    :datetime
#  all_day                   :boolean          default(FALSE), not null
#  display_name              :text
#  created_at                :datetime
#  updated_at                :datetime
#  place_id                  :integer
#  display_name_translations :jsonb            not null
#

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :store_page, only: :index
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]
  before_action :get_library, :get_agent
  before_action :get_libraries, except: :destroy
  before_action :prepare_options
  after_action :convert_charset, only: :index

  # GET /events
  # GET /events.json
  def index
    @count = {}
    query = params[:query].to_s.strip
    @query = query.dup
    query = query.gsub('　', ' ')
    tag = params[:tag].to_s if params[:tag].present?
    date = params[:date].to_s if params[:date].present?
    per_page = ( params[:format] == "json" ) ? 500 : Event.default_per_page
    mode = params[:mode]

    search = Sunspot.new_search(Event)
    library = @library
    search.build do
      fulltext query if query.present?
      with(:library_id).equal_to library.id if library
      # with(:tag).equal_to tag
      if date
        with(:start_at).less_than_or_equal_to Time.zone.parse(date)
        with(:end_at).greater_than Time.zone.parse(date)
      end
      if params[:start].present? and params[:end].present?
        with(:start_at).greater_than_or_equal_to Time.zone.parse(params[:start])
        with(:end_at).less_than_or_equal_to Time.zone.parse(params[:end]).end_of_day
      end
      case mode
      when 'upcoming'
        with(:start_at).greater_than Time.zone.now.beginning_of_day
      when 'past'
        with(:start_at).less_than Time.zone.now.beginning_of_day
      end
      order_by(:start_at, :desc)
    end

    page = params[:page] || 1
    search.query.paginate(page.to_i, per_page)
    @events = search.execute!.results
    @count[:query_result] = @events.total_entries

    respond_to do |format|
      format.html # index.html.erb
      format.json
      format.rss  { render layout: false }
      format.text
      format.atom
      format.ics
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
     prepare_options
     if params[:date]
       begin
         date = Time.zone.parse(params[:date])
       rescue ArgumentError
         date = Time.zone.now.beginning_of_day
         flash[:notice] = t('page.invalid_date')
       end
     else
       date = Time.zone.now.beginning_of_day
     end
     @event = Event.new(start_at: date, end_at: date)
     @event.library = @library

     respond_to do |format|
       format.html # new.html.erb
       format.json { render json: @event }
     end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    prepare_options
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.set_date

    respond_to do |format|
      if @event.save
        flash[:notice] = t('controller.successfully_created', model: t('activerecord.models.event'))
        format.html { redirect_to(@event) }
        format.json { render json: @event, status: :created, location: @event }
      else
        prepare_options
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    @event.set_date

    respond_to do |format|
      if @event.update(event_params)

        flash[:notice] = t('controller.successfully_updated', model: t('activerecord.models.event'))
        format.html { redirect_to(@event) }
        format.json { head :no_content }
      else
        prepare_options
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def check_policy
    authorize Event
  end

  def event_params
    params.require(:event).permit(
      :library_id, :event_category_id, :name, :note, :start_at,
      :end_at, :all_day, :display_name
    )
  end

  def prepare_options
    @event_categories = EventCategory.all
  end

  def filtered_params
    params.permit([:format, :library_id, :mode, :query, :page, :per_page])
  end

  helper_method :filtered_params
end

app/views/events/_all_day.html.erb
<script language="javascript">
  $(document).ready(function() {
    if ($('input:checkbox#event_all_day').is(':checked')) {
      $('#event_start_at_4i').attr('disabled', true);
      $('#event_start_at_5i').attr('disabled', true);
      $('#event_end_at_4i').attr('disabled', true);
      $('#event_end_at_5i').attr('disabled', true);
    }

    $('input:checkbox#event_all_day').click(function() {
      if ($(this).is(':checked')) {
        $('#event_start_at_4i').attr('disabled', true);
        $('#event_start_at_5i').attr('disabled', true);
        $('#event_end_at_4i').attr('disabled', true);
        $('#event_end_at_5i').attr('disabled', true);
      } else {
        $('#event_start_at_4i').attr('disabled', false);
        $('#event_start_at_5i').attr('disabled', false);
        $('#event_end_at_4i').attr('disabled', false);
        $('#event_end_at_5i').attr('disabled', false);
      }
    });
  });
</script>

app/views/events/_calendar.html.erb
    <p>
    </p>

    <div id="calendar"></div>

<script>
  $(document).ready(function() {
    $('#calendar').fullCalendar({
      events: '<%= url_for(params.permit.merge(format: :json, only_path: true)) %>',
      lang: '<%= @locale.to_s %>'
    });
  });
</script>

app/views/events/_form.html.erb
<%= simple_form_for(@event, validate: true) do |f| -%>
  <%= f.error_messages %>

  <div class="form-group">
    <%= f.label t('activerecord.models.event_category') -%><br />
    <%= f.select(:event_category_id, @event_categories.collect{|e| [e.display_name, e.id]}) -%>
  </div>

  <div class="form-group">
    <%= f.label t('activerecord.models.library') -%><br />
    <%= f.select(:library_id, @libraries.collect{|l| [l.display_name, l.id]}) -%>
  </div>

  <div class="form-group">
    <%= f.label :name -%><br />
    <%= f.text_field :name, class: 'resource_title' -%>
  </div>

  <div class="form-group">
    <%= f.label :display_name -%><br />
    <%= f.text_area :display_name, class: 'form-control' -%>
  </div>

  <div class="form-group">
    <%= f.label :start_at -%><br />
    <%= f.datetime_select :start_at -%>
    <%= f.label :all_day -%>
    <%= f.check_box :all_day -%>
  </div>

  <div class="form-group">
    <%= f.label :end_at -%><br />
    <%= f.datetime_select :end_at -%>
  </div>

  <div class="form-group">
    <%= f.label :note -%><br />
    <%= f.text_area :note, class: 'form-control' -%>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<%- end -%>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.editing', model: t('activerecord.models.event')) -%></h1>
    <%= render 'form' %>
    <%= render 'all_day' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.show'), @event -%></li>
        <li><%= link_to t('page.back'), events_path(page: flash[:page] ||= nil) -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.listing', model: t('activerecord.models.event')) -%></h1>
<div id="content_list">
<p id="notice"><%= notice %></p>

<%- if @library -%>
  <h2><%= link_to @library.display_name.localize, @library -%></h2>
<%- else -%>
  <h2><%= t('event.all_libraries') -%></h2>
<%- end -%>

<% if params[:mode] == 'calendar' %>
  <%= render 'calendar' %>
<% else %>
  <%= form_for :events, url: events_path, html: {method: 'get'} do -%>
    <p>
      <%= label_tag :search_form_top, t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {id: 'search_form_top', class: 'search_form', placeholder: t('page.search_term')} -%>
      <%= submit_tag t('page.search') -%>
    </p>
  <%- end -%>

  <p>
    <%- case params[:mode]
      when 'upcoming' -%>
      <%= link_to t('event.all'), url_for(filtered_params.merge(mode: nil, only_path: true)) -%>
      <strong><%= t('event.upcoming') -%></strong>
      <%= link_to t('event.past'), url_for(filtered_params.merge(mode: 'past', only_path: true)) -%>
    <%- when 'past' -%>
      <%= link_to t('event.all'), url_for(filtered_params.merge(mode: nil, only_path: true)) -%>
      <%= link_to t('event.upcoming'), url_for(filtered_params.merge(mode: 'upcoming', only_path: true)) -%>
      <strong><%= t('event.past') -%></strong>
    <%- else -%>
      <strong><%= t('event.all') -%></strong>
      <%= link_to t('event.upcoming'), url_for(filtered_params.merge(mode: 'upcoming', only_path: true)) -%>
      <%= link_to t('event.past'), url_for(filtered_params.merge(mode: 'past', only_path: true)) -%>
    <%- end -%>
  </p>

  <table class="table table-striped index">
    <tr>
      <th><%= t('activerecord.models.library') -%></th>
      <th><%= t('activerecord.attributes.event.name') -%></th>
      <th></th>
    </tr>

  <%- @events.each_with_index do |event, i| -%>
    <tr class="line<%= cycle("0", "1") -%>">
      <td>
        <%= link_to event.library.display_name.localize, event.library -%>
        <br />
        <%= event.event_category.display_name.localize -%>
      </td>
      <td>
        <%= link_to event.display_name.localize, event -%>
        <br />
        <%= l(event.start_at, format: :short) -%>
        -
        <%= l(event.end_at, format: :short) -%>
      </td>
      <td>
        <%- if policy(event).update? -%>
          <%= link_to t('page.edit'), edit_event_path(event) -%>
        <% end %>
        <%- if policy(event).destroy? -%>
          <%= link_to t('page.destroy'), event, data: {confirm: t('page.are_you_sure')}, method: :delete -%>
        <%- end -%>
      </td>
    </tr>
  <%- end -%>
  </table>

  <%= paginate(@events) -%>
<% end %>
</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <% if params[:mode] == 'calendar' %>
      <li><%= link_to t('event.table'), url_for(filtered_params.merge(mode: nil)) -%></li>
    <% else %>
      <li><%= link_to t('event.calendar'), url_for(filtered_params.merge(mode: 'calendar')) -%></li>
    <% end %>
  </ul>
  <ul>
    <%- if user_signed_in? -%>
      <%- if current_user.has_role?('Librarian') -%>
        <%- if @library -%>
          <li><%= link_to t('page.new', model: t('activerecord.models.event')), new_event_path(library_id: @library.name) -%></li>
        <%- else -%>
          <li><%= link_to t('page.new', model: t('activerecord.models.event')), new_event_path(date: params[:date]) -%></li>
        <%- end -%>
        <li><%= link_to t('event.import_event'), event_import_files_path -%></li>
      <%- end -%>
    <%- end -%>
  </ul>
  <ul>
    <li><%= link_to t('event.all_libraries'), url_for(filtered_params.merge(library_id: nil, page: nil)) -%></li>
    <%- @libraries.each do |library| -%>
      <li><%= link_to library.display_name.localize, url_for(filtered_params.merge(library_id: library.name, mode: params[:mode])) -%></li>
    <%- end -%>
  </ul>
  <p>
    <%- if @library -%>
      <%= link_to (image_tag 'icons/feed.png', size: '16x16', class: 'enju_icon', alt: t('page.feed')), url_for(filtered_params.merge(library_id: @library.name, format: :rss, page: nil)) -%>
      (<%= link_to 'RSS', url_for(filtered_params.merge(library_id: @library.name, format: :rss, page: nil)) -%>)
      <%= link_to (image_tag 'icons/page_white_excel.png', size: '16x16', class: 'enju_icon', alt: 'TSV'), url_for(filtered_params.merge(library_id: @library.name, format: :txt, locale: @locale.to_s)) -%>
      (<%= link_to 'TSV', url_for(filtered_params.merge(library_id: @library.name, format: :txt, locale: @locale.to_s)) -%>)
      <br />
      <%= link_to (image_tag 'icons/calendar.png', size: '16x16', class: 'enju_icon', alt: 'iCalendar'), url_for(filtered_params.merge(library_id: @library.name, format: :ics, locale: @locale.to_s)) -%>
      (<%= link_to 'iCalendar', url_for(filtered_params.merge(library_id: @library.name, format: :ics, locale: @locale.to_s)) -%>)
    <%- else -%>
      <%= link_to (image_tag 'icons/feed.png', size: '16x16', class: 'enju_icon', alt: t('page.feed')), url_for(filtered_params.merge(format: :rss)) -%>
      (<%= link_to 'RSS', url_for(filtered_params.merge(format: :rss)) -%>)
      <%= link_to (image_tag 'icons/page_white_excel.png', size: '16x16', class: 'enju_icon', alt: 'TSV'), url_for(filtered_params.merge(format: :txt, locale: @locale.to_s)) -%>
      (<%= link_to 'TSV', url_for(filtered_params.merge(format: :txt, locale: @locale.to_s)) -%>)
      <br />
      <%= link_to (image_tag 'icons/calendar.png', size: '16x16', class: 'enju_icon', alt: 'iCalendar'), url_for(filtered_params.merge(format: :ics, locale: @locale.to_s)) -%>
      (<%= link_to 'iCalendar', url_for(filtered_params.merge(format: :ics, locale: @locale.to_s)) -%>)
    <%- end -%>
  </p>
</div>

app/views/events/index.ics.erb
<%=
events = @events
RiCal.Calendar do
  events.each do |event|
    event do
      description event.display_name.localize
      dtstart     event.start_at
      dtend       event.end_at
      location    event.library.address
    end
  end
end.to_s
-%>

app/views/events/index.mobile.erb
<div data-role="header">
<h1 class="title"><%= t('page.listing', model: t('activerecord.models.event')) -%></h1>
</div>

<div data-role="content">
<%- if @library -%>
  <h2><%= link_to @library.display_name.localize, @library -%></h2>
<%- else -%>
  <h2><%= t('event.all_libraries') -%></h2>
<%- end -%>

  <div data-role="fieldcontain">
    <%= form_for :events, url: events_path, html: {method: 'get'} do -%>
      <p>
        <%= label_tag :search_form_top, t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {id: 'search_form_top', class: 'search_form', placeholder: t('page.search_term')} -%>
        <%= submit_tag t('page.search') -%>
      </p>
    <%- end -%>
  </div>

<p>
  <%- case params[:mode]
      when 'upcoming' -%>
    <%= link_to t('event.all'), url_for(params.merge(mode: nil, only_path: true)) -%>
    <strong><%= t('event.upcoming') -%></strong>
    <%= link_to t('event.past'), url_for(params.merge(mode: 'past', only_path: true)) -%>
  <%- when 'past' -%>
    <%= link_to t('event.all'), url_for(params.merge(mode: nil, only_path: true)) -%>
    <%= link_to t('event.upcoming'), url_for(params.merge(mode: 'upcoming', only_path: true)) -%>
    <strong><%= t('event.past') -%></strong>
  <%- else -%>
    <strong><%= t('event.all') -%></strong>
    <%= link_to t('event.upcoming'), url_for(params.merge(mode: 'upcoming', only_path: true)) -%>
    <%= link_to t('event.past'), url_for(params.merge(mode: 'past', only_path: true)) -%>
  <%- end -%>
</p>
</div>

<ul data-role="listview">
  <%- @events.each_with_index do |event, i| -%>
    <li>
      <%= link_to event.display_name.localize, event -%>
      <br />
      <%= l(event.start_at, format: :short) -%>
      -
      <%= l(event.end_at, format: :short) -%>
    </li>
  <%- end -%>
</ul>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.new', model: t('activerecord.models.event')) -%></h1>
    <%= render 'form' %>
    <%= render 'all_day' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if @library -%>
          <li><%= link_to t('page.back'), events_path(library_id: @library.name) -%></li>
        <%- else -%>
          <li><%= link_to t('page.back'), events_path -%></li>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-9">
  <h1 class="title"><%= t('page.showing', model: t('activerecord.models.event')) -%></h1>
    <p id="notice"><%= notice %></p>

    <h2 class="resource_title">
      <%= @event.display_name -%>
    </h2>

    <p>
      <strong><%= t('activerecord.attributes.event.name') -%>:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong><%= t('activerecord.models.event_category') -%>:</strong>
      <%= @event.event_category.display_name -%>
    </p>

    <p>
      <strong><%= t('activerecord.models.library') -%>:</strong>
      <%= link_to @event.library.display_name, @event.library -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event.start_at') -%>:</strong>
      <% if @event.all_day %>
        <%= l(@event.start_at, format: :only_date) -%>
      <% else %>
        <%= l(@event.start_at) -%>
      <% end %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event.end_at') -%>:</strong>
      <% if @event.all_day %>
        <%= l(@event.end_at, format: :only_date) -%>
      <% else %>
        <%= l(@event.end_at) -%>
      <% end %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event.all_day') -%>:</strong>
      <%= localized_boolean(@event.all_day) %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event.note') -%>:</strong>
      <%= raw auto_link(simple_format(h(@event.note))) -%>
    </p>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(@event).update? -%>
          <li><%= link_to t('page.edit'), edit_event_path(@event) -%></li>
        <% end %>
        <% if policy(@event).destroy? %>
          <li><%= link_to t('page.destroy'), @event, data: {confirm: t('page.are_you_sure')}, method: :delete -%></li>
        <% end %>
        <li><%= back_to_index(flash[:page_info]) -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/events/show.mobile.erb
<div data-role="header">
  <h1 class="title"><%= t('page.showing', model: t('activerecord.models.event')) -%></h1>
</div>

<div data-role="content">
<h2 class="resource_title">
  <%= @event.display_name.localize -%>
</h2>

<p>
  <strong><%= t('activerecord.models.event_category') -%>:</strong>
  <%= @event.event_category.display_name.localize -%>
</p>

<p>
  <strong><%= t('activerecord.models.library') -%>:</strong>
  <%= link_to @event.library.display_name.localize, @event.library -%>
</p>

<%- if @event.all_day -%>
  <p>
    <strong><%= t('activerecord.attributes.event.all_day') -%>:</strong>
    <%= l(@event.start_at, format: :only_date) -%>
  </p>
<%- else -%>
  <p>
    <strong><%= t('activerecord.attributes.event.start_at') -%>:</strong>
    <%= l(@event.start_at, format: :short) -%>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.event.end_at') -%>:</strong>
    <%= l(@event.end_at, format: :short) -%>
  </p>
<%- end -%>

<p>
  <strong><%= t('activerecord.attributes.event.note') -%>:</strong>
  <%= raw auto_link(simple_format(h(@event.note))) -%>
</p>

</div>