config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :event_export_files

  resources :event_import_files

  resources :events
  resources :event_categories
  resources :event_import_results, only: [:index, :show, :destroy]
  resources :participates
end

app/models/event_export_file.rb
class EventExportFile < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries[
    transition_class: EventExportFileTransition,
    initial_state: :pending
  ]
  include ExportFile

  if ENV['ENJU_STORAGE'] == 's3'
    has_attached_file :event_export, storage: :s3,
      s3_credentials: {
        access_key: ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        bucket: ENV['S3_BUCKET_NAME'],
        s3_host_name: ENV['S3_HOST_NAME']
      },
      s3_permissions: :private
  else
    has_attached_file :event_export,
      path: ":rails_root/private/system/:class/:attachment/:id_partition/:style/:filename"
  end
  validates_attachment_content_type :event_export, content_type: /\Atext\/plain\Z/
  has_many :event_export_file_transitions, autosave: false

  def state_machine
    EventExportFileStateMachine.new(self, transition_class: EventExportFileTransition)
  end

  delegate :can_transition_to?, :transition_to!, :transition_to, :current_state,
    to: :state_machine

  def export!
    role_name = user.try(:role).try(:name)
    tsv = Event.export(role: role_name)

    EventExportFile.transaction do
      transition_to!(:started)
      role_name = user.try(:role).try(:name)
      self.event_export = StringIO.new(tsv)
      self.event_export.instance_write(:filename, "event_export.txt")
      save!
      transition_to!(:completed)
    end
    mailer = EventExportMailer.completed(self)
    send_message(mailer)
  rescue => e
    transition_to!(:failed)
    mailer = EventExportMailer.failed(self)
    send_message(mailer)
    raise e
  end
end

# == Schema Information
#
# Table name: event_export_files
#
#  id                        :integer          not null, primary key
#  user_id                   :integer
#  event_export_file_name    :string
#  event_export_content_type :string
#  event_export_file_size    :bigint
#  event_export_updated_at   :datetime
#  executed_at               :datetime
#  created_at                :datetime
#  updated_at                :datetime
#

app/controllers/event_export_files_controller.rb
class EventExportFilesController < ApplicationController
  before_action :set_event_export_file, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]

  # GET /event_export_files
  # GET /event_export_files.json
  def index
    @event_export_files = EventExportFile.order('id DESC').page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_export_files }
    end
  end

  # GET /event_export_files/1
  # GET /event_export_files/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_export_file }
      format.download {
        send_data @event_export_file.event_export.download, fileename: @event_export_file.event_export.filename.to_s, type: 'application/octet-stream'
      }
    end
  end

  # GET /event_export_files/new
  # GET /event_export_files/new.json
  def new
    @event_export_file = EventExportFile.new
    @event_export_file.user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_export_file }
    end
  end

  # GET /event_export_files/1/edit
  def edit
  end

  # POST /event_export_files
  # POST /event_export_files.json
  def create
    @event_export_file = EventExportFile.new(event_export_file_params)
    @event_export_file.user = current_user

    respond_to do |format|
      if @event_export_file.save
        if @event_export_file.mode == 'export'
          EventExportFileJob.perform_later(@event_export_file)
        end
        format.html { redirect_to @event_export_file, notice: t('export.successfully_created', model: t('activerecord.models.event_export_file')) }
        format.json { render json: @event_export_file, status: :created, location: @event_export_file }
      else
        format.html { render action: "new" }
        format.json { render json: @event_export_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_export_files/1
  # PUT /event_export_files/1.json
  def update
    respond_to do |format|
      if @event_export_file.update(event_export_file_params)
        if @event_export_file.mode == 'export'
          EventExportFileJob.perform_later(@event_export_file)
        end
        format.html { redirect_to @event_export_file, notice: t('controller.successfully_updated', model: t('activerecord.models.event_export_file')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_export_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_export_files/1
  # DELETE /event_export_files/1.json
  def destroy
    @event_export_file.destroy

    respond_to do |format|
      format.html { redirect_to event_export_files_url }
      format.json { head :no_content }
    end
  end

  private
  def set_event_export_file
    @event_export_file = EventExportFile.find(params[:id])
    authorize @event_export_file
  end

  def check_policy
    authorize EventExportFile
  end

  def event_export_file_params
    params.require(:event_export_file).permit(:mode)
  end
end

app/views/event_export_files/_form.html.erb
<%= form_for(@event_export_file) do |f| %>
  <%= f.error_messages %>

  <%= f.hidden_field :mode, value: 'export' if @event_export_file.new_record? %>
  <div class="actions">
    <% if @event_export_file.new_record? %>
      <%= f.submit t('page.export'), class: 'btn btn-primary' %>
    <% else %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/event_export_files/edit.html.erb
<h1>Editing event_export_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_export_file %> |
<%= link_to 'Back', event_export_files_path %>

app/views/event_export_files/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.listing', model: t('activerecord.models.event_export_file')) -%></h1>

    <table class="table table-striped index">
      <thead>
        <tr>
          <th>Id</th>
          <th><%= t('activerecord.models.user') %></th>
          <th><%= t('activerecord.attributes.event_export_file.event_export_file_name') -%></th>
          <th><%= t('activerecord.attributes.event_export_file.state') -%></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @event_export_files.each do |event_export_file| %>
          <tr class="line<%= cycle("0", "1") -%>">
            <td><%= link_to event_export_file.id, event_export_file %></td>
            <td><%= event_export_file.user.try(:username) %></td>
            <td>
              <%= link_to event_export_file.attachment.filename.to_s, event_export_file_path(event_export_file, format: :download) if event_export_file.attachment.attached? %>
              <br />
              <%= event_export_file.created_at %>
            </td>
            <td><%= localized_state(event_export_file.current_state) -%></td>
            <td>
              <%= link_to t('page.destroy'), event_export_file, data: {confirm: t('page.are_you_sure')}, method: :delete -%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate(@event_export_files) %>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.new', model: t('activerecord.models.event_export_file')), new_event_export_file_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/event_export_files/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.new', model: t('activerecord.models.event_export_file')) -%></h1>

    <p><%= t('export.are_you_sure_to_export') %></p>

    <%= render 'form' %>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.listing', model: t('activerecord.models.event_export_file')), event_export_files_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/event_export_files/show.html.erb
<div class="row">
  <div id="content_detail" class="ui-corner-all ui-widget-content">
    <h1 class="title"><%= t('page.showing', model: t('activerecord.models.event_export_file')) -%></h1>
    <p id="notice"><%= notice %></p>

    <p>
      <strong><%= t('activerecord.models.user') %></strong>
      <%= @event_export_file.user&.username %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_export_file.event_export_file_name') -%></strong>
      <%= link_to @event_export_file.event_export_file_name, event_export_file_path(@event_export_file, format: :download) if @event_export_file.event_export? %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.event_export_file.state') -%>:</strong>
      <%= localized_state(@event_export_file.current_state) -%>
    </p>

    <p>
      <strong><%= t('page.created_at') -%>:</strong>
      <%=l @event_export_file.created_at -%>
    </p>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= back_to_index(flash[:page_info]) -%></li>
        <% if current_user.has_role?('Administrator') %>
          <% if defined?(Resque) %>
            <li><%= link_to 'Resque', resque_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>